export const auras = [
  {
    "id": "aura_0",
    "name": "Digital Matrix Rain",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "free",
    "rarity": "common",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_1",
    "name": "Emerald Matrix Rain",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "free",
    "rarity": "common",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_2",
    "name": "Binary Matrix Rain",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "free",
    "rarity": "common",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_3",
    "name": "Cascading Matrix Rain",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_4",
    "name": "Cryptic Matrix Rain",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_5",
    "name": "Digital Code Stream",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_6",
    "name": "Emerald Code Stream",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_7",
    "name": "Binary Code Stream",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_8",
    "name": "Cascading Code Stream",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_9",
    "name": "Cryptic Code Stream",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_10",
    "name": "Digital Data Cascade",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_11",
    "name": "Emerald Data Cascade",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_12",
    "name": "Binary Data Cascade",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_13",
    "name": "Cascading Data Cascade",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_14",
    "name": "Cryptic Data Cascade",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_15",
    "name": "Digital Terminal Waterfall",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_16",
    "name": "Emerald Terminal Waterfall",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_17",
    "name": "Binary Terminal Waterfall",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_18",
    "name": "Cascading Terminal Waterfall",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_19",
    "name": "Cryptic Terminal Waterfall",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_20",
    "name": "Digital Matrix Rain",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_21",
    "name": "Emerald Matrix Rain",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_22",
    "name": "Binary Matrix Rain",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_23",
    "name": "Cascading Matrix Rain",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_24",
    "name": "Cryptic Matrix Rain",
    "category": "auras",
    "archetype": "matrix_rain",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_25",
    "name": "Orbital Plasma Rings",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "free",
    "rarity": "common",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_26",
    "name": "Chroma Plasma Rings",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "free",
    "rarity": "common",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_27",
    "name": "Singularity Plasma Rings",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "free",
    "rarity": "common",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_28",
    "name": "Particle Plasma Rings",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_29",
    "name": "Flux Plasma Rings",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_30",
    "name": "Orbital Ion Halo",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_31",
    "name": "Chroma Ion Halo",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_32",
    "name": "Singularity Ion Halo",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_33",
    "name": "Particle Ion Halo",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_34",
    "name": "Flux Ion Halo",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_35",
    "name": "Orbital Energy Orbit",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_36",
    "name": "Chroma Energy Orbit",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_37",
    "name": "Singularity Energy Orbit",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_38",
    "name": "Particle Energy Orbit",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_39",
    "name": "Flux Energy Orbit",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_40",
    "name": "Orbital Charged Gyro",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_41",
    "name": "Chroma Charged Gyro",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_42",
    "name": "Singularity Charged Gyro",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_43",
    "name": "Particle Charged Gyro",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_44",
    "name": "Flux Charged Gyro",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_45",
    "name": "Orbital Plasma Rings",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_46",
    "name": "Chroma Plasma Rings",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_47",
    "name": "Singularity Plasma Rings",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_48",
    "name": "Particle Plasma Rings",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_49",
    "name": "Flux Plasma Rings",
    "category": "auras",
    "archetype": "plasma_ring",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_50",
    "name": "Ethereal Quantum Mist",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "free",
    "rarity": "common",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_51",
    "name": "Nebula Quantum Mist",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "free",
    "rarity": "common",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_52",
    "name": "Cryo Quantum Mist",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "free",
    "rarity": "common",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_53",
    "name": "Cosmic Quantum Mist",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_54",
    "name": "Void Quantum Mist",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_55",
    "name": "Ethereal Spectral Vapor",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_56",
    "name": "Nebula Spectral Vapor",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_57",
    "name": "Cryo Spectral Vapor",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_58",
    "name": "Cosmic Spectral Vapor",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_59",
    "name": "Void Spectral Vapor",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_60",
    "name": "Ethereal Stardust Cloud",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_61",
    "name": "Nebula Stardust Cloud",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_62",
    "name": "Cryo Stardust Cloud",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_63",
    "name": "Cosmic Stardust Cloud",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_64",
    "name": "Void Stardust Cloud",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_65",
    "name": "Ethereal Chrono Haze",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_66",
    "name": "Nebula Chrono Haze",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_67",
    "name": "Cryo Chrono Haze",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_68",
    "name": "Cosmic Chrono Haze",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_69",
    "name": "Void Chrono Haze",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_70",
    "name": "Ethereal Quantum Mist",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_71",
    "name": "Nebula Quantum Mist",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_72",
    "name": "Cryo Quantum Mist",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_73",
    "name": "Cosmic Quantum Mist",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_74",
    "name": "Void Quantum Mist",
    "category": "auras",
    "archetype": "quantum_mist",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_75",
    "name": "Flickering Glitch Halo",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "free",
    "rarity": "common",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_76",
    "name": "Overclocked Glitch Halo",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "free",
    "rarity": "common",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_77",
    "name": "Holographic Glitch Halo",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "free",
    "rarity": "common",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_78",
    "name": "Runic Glitch Halo",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_79",
    "name": "Crowned Glitch Halo",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_80",
    "name": "Flickering Crown of Code",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_81",
    "name": "Overclocked Crown of Code",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_82",
    "name": "Holographic Crown of Code",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_83",
    "name": "Runic Crown of Code",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_84",
    "name": "Crowned Crown of Code",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_85",
    "name": "Flickering Hex Sigil",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_86",
    "name": "Overclocked Hex Sigil",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_87",
    "name": "Holographic Hex Sigil",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_88",
    "name": "Runic Hex Sigil",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_89",
    "name": "Crowned Hex Sigil",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_90",
    "name": "Flickering Vortex Crown",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_91",
    "name": "Overclocked Vortex Crown",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_92",
    "name": "Holographic Vortex Crown",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_93",
    "name": "Runic Vortex Crown",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_94",
    "name": "Crowned Vortex Crown",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_95",
    "name": "Flickering Glitch Halo",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_96",
    "name": "Overclocked Glitch Halo",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_97",
    "name": "Holographic Glitch Halo",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_98",
    "name": "Runic Glitch Halo",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  },
  {
    "id": "aura_99",
    "name": "Crowned Glitch Halo",
    "category": "auras",
    "archetype": "glitch_halo",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Ambient 3D volumetric visual effect radiating around the agent workstation with animated particle depth."
  }
];
