/**
 * Virtual Office Themes & Wallpapers Catalog
 * Defines floor environments, neon grids, color palettes, and ambient lighting
 * for the 2D PixiJS Virtual Office Canvas.
 */

export const officeThemes = [
  {
    id: "theme_default",
    name: "Classic Charcoal Slate",
    tier: "free",
    category: "themes",
    description: "Default minimalist dark charcoal slate floor with subtle grid lines.",
    palette: {
      floorGradient: [0x0b1018, 0x161f2c],
      gridColor: 0x1a2330,
      gridAlpha: 0.7,
      borderColor: 0x263244,
      panelRackColor: 0xfde047,
      panelPodColor: 0x22d3ee,
      accentColor: "#007acc",
      ambientGlow: "#007acc33",
    },
  },
  {
    id: "theme_cyberpunk",
    name: "Cyberpunk Neon Night",
    tier: "free",
    category: "themes",
    description: "Futuristic nighttime cyber alley with high-contrast violet grids and cyan radiance.",
    palette: {
      floorGradient: [0x0d071a, 0x180b30],
      gridColor: 0x6d28d9,
      gridAlpha: 0.75,
      borderColor: 0xa855f7,
      panelRackColor: 0xf43f5e,
      panelPodColor: 0x06b6d4,
      accentColor: "#a855f7",
      ambientGlow: "#a855f733",
    },
  },
  {
    id: "theme_matrix",
    name: "Phosphor Matrix Terminal",
    tier: "free",
    category: "themes",
    description: "Retro monochrome CRT terminal floor with glowing emerald phosphor matrix coordinates.",
    palette: {
      floorGradient: [0x030d07, 0x071e11],
      gridColor: 0x10b981,
      gridAlpha: 0.8,
      borderColor: 0x059669,
      panelRackColor: 0x34d399,
      panelPodColor: 0x10b981,
      accentColor: "#10b981",
      ambientGlow: "#10b98133",
    },
  },
  {
    id: "theme_cozy_loft",
    name: "Cozy Scandinavian Loft",
    tier: "coffee",
    category: "themes",
    description: "Warm espresso and natural walnut wooden floor texture with amber ambient lighting.",
    palette: {
      floorGradient: [0x1c1612, 0x2b211a],
      gridColor: 0x453528,
      gridAlpha: 0.65,
      borderColor: 0x78563a,
      panelRackColor: 0xf59e0b,
      panelPodColor: 0xd97706,
      accentColor: "#f59e0b",
      ambientGlow: "#f59e0b33",
    },
  },
  {
    id: "theme_deep_space",
    name: "Deep Cosmic Nebula",
    tier: "coffee",
    category: "themes",
    description: "Deep space observation deck with star cluster reflections and celestial indigo accents.",
    palette: {
      floorGradient: [0x050814, 0x0e1429],
      gridColor: 0x38bdf8,
      gridAlpha: 0.65,
      borderColor: 0x0284c7,
      panelRackColor: 0x818cf8,
      panelPodColor: 0x38bdf8,
      accentColor: "#38bdf8",
      ambientGlow: "#38bdf833",
    },
  },
  {
    id: "theme_cleanroom",
    name: "Silicon Fab Cleanroom",
    tier: "lunch",
    category: "themes",
    description: "High-precision sterile semiconductor laboratory with sleek platinum and ice blue lines.",
    palette: {
      floorGradient: [0x141820, 0x1e2430],
      gridColor: 0x475569,
      gridAlpha: 0.7,
      borderColor: 0x94a3b8,
      panelRackColor: 0x38bdf8,
      panelPodColor: 0x0ea5e9,
      accentColor: "#94a3b8",
      ambientGlow: "#94a3b833",
    },
  },
  {
    id: "theme_synthwave",
    name: "Sunset Synthwave 80s",
    tier: "lunch",
    category: "themes",
    description: "Vibrant retro-wave sunset floor with magenta neon grid lines and warm golden horizon.",
    palette: {
      floorGradient: [0x200720, 0x360d2b],
      gridColor: 0xf43f5e,
      gridAlpha: 0.75,
      borderColor: 0xfb7185,
      panelRackColor: 0xfbbf24,
      panelPodColor: 0xec4899,
      accentColor: "#f43f5e",
      ambientGlow: "#f43f5e33",
    },
  },
  {
    id: "theme_quantum_void",
    name: "Quantum Obsidian Void",
    tier: "vip",
    category: "themes",
    description: "Deep obsidian black hole floor with holographic quantum interference lattice.",
    palette: {
      floorGradient: [0x060608, 0x0f0f14],
      gridColor: 0x6366f1,
      gridAlpha: 0.75,
      borderColor: 0x4f46e5,
      panelRackColor: 0xa855f7,
      panelPodColor: 0x06b6d4,
      accentColor: "#6366f1",
      ambientGlow: "#6366f133",
    },
  },
  {
    id: "theme_sakura_cyber",
    name: "Sakura Cyber Garden",
    tier: "vip",
    category: "themes",
    description: "Neo-Tokyo cherry blossom sanctuary with vibrant soft pink particle gridlines.",
    palette: {
      floorGradient: [0x1f0c18, 0x301326],
      gridColor: 0xf472b6,
      gridAlpha: 0.7,
      borderColor: 0xec4899,
      panelRackColor: 0xfda4af,
      panelPodColor: 0xf43f5e,
      accentColor: "#f472b6",
      ambientGlow: "#f472b633",
    },
  },
  {
    id: "theme_gold_vault",
    name: "Billion-Token Gold Vault",
    tier: "vip",
    category: "themes",
    description: "Luxurious royal vault floor with gleaming gold circuitry and platinum accents.",
    palette: {
      floorGradient: [0x1a1608, 0x2e250c],
      gridColor: 0xeab308,
      gridAlpha: 0.8,
      borderColor: 0xfacc15,
      panelRackColor: 0xfef08a,
      panelPodColor: 0xf59e0b,
      accentColor: "#eab308",
      ambientGlow: "#eab30833",
    },
  },
];
