export const pets = [
  {
    "id": "pet_0",
    "name": "None",
    "category": "pets",
    "archetype": "none",
    "tier": "free",
    "rarity": "common",
    "color": "#64748b",
    "secondaryColor": "#1e293b",
    "paletteName": "Neutral Slate",
    "description": "Clean workstation desk without an active cyber pet."
  },
  {
    "id": "pet_1",
    "name": "Cozy Cyber Cat",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "free",
    "rarity": "common",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_2",
    "name": "Pixel Cyber Cat",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "free",
    "rarity": "common",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_3",
    "name": "Sleek Cyber Cat",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "free",
    "rarity": "common",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_4",
    "name": "Quantum Cyber Cat",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "free",
    "rarity": "common",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_5",
    "name": "Glitch Cyber Cat",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "free",
    "rarity": "common",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_6",
    "name": "Nano Cyber Cat",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_7",
    "name": "Cozy Kitten Bot",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_8",
    "name": "Pixel Kitten Bot",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_9",
    "name": "Sleek Kitten Bot",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_10",
    "name": "Quantum Kitten Bot",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_11",
    "name": "Glitch Kitten Bot",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_12",
    "name": "Nano Kitten Bot",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_13",
    "name": "Cozy Robo Feline",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_14",
    "name": "Pixel Robo Feline",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_15",
    "name": "Sleek Robo Feline",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_16",
    "name": "Quantum Robo Feline",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_17",
    "name": "Glitch Robo Feline",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_18",
    "name": "Nano Robo Feline",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_19",
    "name": "Cozy Visor Kitty",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_20",
    "name": "Pixel Visor Kitty",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_21",
    "name": "Sleek Visor Kitty",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_22",
    "name": "Quantum Visor Kitty",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_23",
    "name": "Glitch Visor Kitty",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_24",
    "name": "Nano Visor Kitty",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_25",
    "name": "Cozy Alloy Prowler",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_26",
    "name": "Pixel Alloy Prowler",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_27",
    "name": "Sleek Alloy Prowler",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_28",
    "name": "Quantum Alloy Prowler",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_29",
    "name": "Glitch Alloy Prowler",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_30",
    "name": "Nano Alloy Prowler",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_31",
    "name": "Cozy Cyber Cat",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_32",
    "name": "Pixel Cyber Cat",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_33",
    "name": "Sleek Cyber Cat",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_34",
    "name": "Quantum Cyber Cat",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_35",
    "name": "Glitch Cyber Cat",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_36",
    "name": "Nano Cyber Cat",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_37",
    "name": "Cozy Kitten Bot",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_38",
    "name": "Pixel Kitten Bot",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_39",
    "name": "Sleek Kitten Bot",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_40",
    "name": "Quantum Kitten Bot",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_41",
    "name": "Glitch Kitten Bot",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_42",
    "name": "Nano Kitten Bot",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_43",
    "name": "Cozy Robo Feline",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_44",
    "name": "Pixel Robo Feline",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_45",
    "name": "Sleek Robo Feline",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_46",
    "name": "Quantum Robo Feline",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_47",
    "name": "Glitch Robo Feline",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_48",
    "name": "Nano Robo Feline",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_49",
    "name": "Cozy Visor Kitty",
    "category": "pets",
    "archetype": "cyber_cat",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_50",
    "name": "Golden Shiba Inu",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "free",
    "rarity": "common",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_51",
    "name": "Loyal Shiba Inu",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "free",
    "rarity": "common",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_52",
    "name": "Sleepy Shiba Inu",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "free",
    "rarity": "common",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_53",
    "name": "Armored Shiba Inu",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "free",
    "rarity": "common",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_54",
    "name": "Mecha Shiba Inu",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "free",
    "rarity": "common",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_55",
    "name": "Solar Shiba Inu",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_56",
    "name": "Golden Corgi Pup",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_57",
    "name": "Loyal Corgi Pup",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_58",
    "name": "Sleepy Corgi Pup",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_59",
    "name": "Armored Corgi Pup",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_60",
    "name": "Mecha Corgi Pup",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_61",
    "name": "Solar Corgi Pup",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_62",
    "name": "Golden Cyber Hound",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_63",
    "name": "Loyal Cyber Hound",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_64",
    "name": "Sleepy Cyber Hound",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_65",
    "name": "Armored Cyber Hound",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_66",
    "name": "Mecha Cyber Hound",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_67",
    "name": "Solar Cyber Hound",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_68",
    "name": "Golden Watch Dog",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_69",
    "name": "Loyal Watch Dog",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_70",
    "name": "Sleepy Watch Dog",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_71",
    "name": "Armored Watch Dog",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_72",
    "name": "Mecha Watch Dog",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_73",
    "name": "Solar Watch Dog",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_74",
    "name": "Golden Patrol Canine",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_75",
    "name": "Loyal Patrol Canine",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_76",
    "name": "Sleepy Patrol Canine",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_77",
    "name": "Armored Patrol Canine",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_78",
    "name": "Mecha Patrol Canine",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_79",
    "name": "Solar Patrol Canine",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_80",
    "name": "Golden Shiba Inu",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_81",
    "name": "Loyal Shiba Inu",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_82",
    "name": "Sleepy Shiba Inu",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_83",
    "name": "Armored Shiba Inu",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_84",
    "name": "Mecha Shiba Inu",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_85",
    "name": "Solar Shiba Inu",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_86",
    "name": "Golden Corgi Pup",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_87",
    "name": "Loyal Corgi Pup",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_88",
    "name": "Sleepy Corgi Pup",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_89",
    "name": "Armored Corgi Pup",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_90",
    "name": "Mecha Corgi Pup",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_91",
    "name": "Solar Corgi Pup",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_92",
    "name": "Golden Cyber Hound",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_93",
    "name": "Loyal Cyber Hound",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_94",
    "name": "Sleepy Cyber Hound",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_95",
    "name": "Armored Cyber Hound",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_96",
    "name": "Mecha Cyber Hound",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_97",
    "name": "Solar Cyber Hound",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_98",
    "name": "Golden Watch Dog",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_99",
    "name": "Loyal Watch Dog",
    "category": "pets",
    "archetype": "dozing_shiba",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_100",
    "name": "Orbital Hover Drone",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "free",
    "rarity": "common",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_101",
    "name": "Scout Hover Drone",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "free",
    "rarity": "common",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_102",
    "name": "Floating Hover Drone",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "free",
    "rarity": "common",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_103",
    "name": "Aero Hover Drone",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "free",
    "rarity": "common",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_104",
    "name": "Sentry Hover Drone",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "free",
    "rarity": "common",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_105",
    "name": "Patrol Hover Drone",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_106",
    "name": "Orbital Orb Companion",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_107",
    "name": "Scout Orb Companion",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_108",
    "name": "Floating Orb Companion",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_109",
    "name": "Aero Orb Companion",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_110",
    "name": "Sentry Orb Companion",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_111",
    "name": "Patrol Orb Companion",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_112",
    "name": "Orbital Sensor Eye",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_113",
    "name": "Scout Sensor Eye",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_114",
    "name": "Floating Sensor Eye",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_115",
    "name": "Aero Sensor Eye",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_116",
    "name": "Sentry Sensor Eye",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_117",
    "name": "Patrol Sensor Eye",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_118",
    "name": "Orbital Surveyor Pod",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_119",
    "name": "Scout Surveyor Pod",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_120",
    "name": "Floating Surveyor Pod",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_121",
    "name": "Aero Surveyor Pod",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_122",
    "name": "Sentry Surveyor Pod",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_123",
    "name": "Patrol Surveyor Pod",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_124",
    "name": "Orbital Aero Familiar",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_125",
    "name": "Scout Aero Familiar",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_126",
    "name": "Floating Aero Familiar",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_127",
    "name": "Aero Aero Familiar",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_128",
    "name": "Sentry Aero Familiar",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_129",
    "name": "Patrol Aero Familiar",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_130",
    "name": "Orbital Hover Drone",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_131",
    "name": "Scout Hover Drone",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_132",
    "name": "Floating Hover Drone",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_133",
    "name": "Aero Hover Drone",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_134",
    "name": "Sentry Hover Drone",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_135",
    "name": "Patrol Hover Drone",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_136",
    "name": "Orbital Orb Companion",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_137",
    "name": "Scout Orb Companion",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_138",
    "name": "Floating Orb Companion",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_139",
    "name": "Aero Orb Companion",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_140",
    "name": "Sentry Orb Companion",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_141",
    "name": "Patrol Orb Companion",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_142",
    "name": "Orbital Sensor Eye",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_143",
    "name": "Scout Sensor Eye",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_144",
    "name": "Floating Sensor Eye",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_145",
    "name": "Aero Sensor Eye",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_146",
    "name": "Sentry Sensor Eye",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_147",
    "name": "Patrol Sensor Eye",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_148",
    "name": "Orbital Surveyor Pod",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_149",
    "name": "Scout Surveyor Pod",
    "category": "pets",
    "archetype": "hover_drone",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_150",
    "name": "Clockwork Cyber Owl",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "free",
    "rarity": "common",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_151",
    "name": "Wise Cyber Owl",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "free",
    "rarity": "common",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_152",
    "name": "Obsidian Cyber Owl",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "free",
    "rarity": "common",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_153",
    "name": "Brass Cyber Owl",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "free",
    "rarity": "common",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_154",
    "name": "Nocturnal Cyber Owl",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "free",
    "rarity": "common",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_155",
    "name": "Optic Cyber Owl",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_156",
    "name": "Clockwork Gear Raven",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_157",
    "name": "Wise Gear Raven",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_158",
    "name": "Obsidian Gear Raven",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_159",
    "name": "Brass Gear Raven",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_160",
    "name": "Nocturnal Gear Raven",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_161",
    "name": "Optic Gear Raven",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_162",
    "name": "Clockwork Falcon Bot",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_163",
    "name": "Wise Falcon Bot",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_164",
    "name": "Obsidian Falcon Bot",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_165",
    "name": "Brass Falcon Bot",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_166",
    "name": "Nocturnal Falcon Bot",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_167",
    "name": "Optic Falcon Bot",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_168",
    "name": "Clockwork Aero Hawk",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_169",
    "name": "Wise Aero Hawk",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_170",
    "name": "Obsidian Aero Hawk",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_171",
    "name": "Brass Aero Hawk",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_172",
    "name": "Nocturnal Aero Hawk",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_173",
    "name": "Optic Aero Hawk",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_174",
    "name": "Clockwork Bionic Bird",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_175",
    "name": "Wise Bionic Bird",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_176",
    "name": "Obsidian Bionic Bird",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_177",
    "name": "Brass Bionic Bird",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_178",
    "name": "Nocturnal Bionic Bird",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_179",
    "name": "Optic Bionic Bird",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_180",
    "name": "Clockwork Cyber Owl",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_181",
    "name": "Wise Cyber Owl",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_182",
    "name": "Obsidian Cyber Owl",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_183",
    "name": "Brass Cyber Owl",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_184",
    "name": "Nocturnal Cyber Owl",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_185",
    "name": "Optic Cyber Owl",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_186",
    "name": "Clockwork Gear Raven",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_187",
    "name": "Wise Gear Raven",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_188",
    "name": "Obsidian Gear Raven",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_189",
    "name": "Brass Gear Raven",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  },
  {
    "id": "pet_190",
    "name": "Nocturnal Gear Raven",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and cyber cyan trim."
  },
  {
    "id": "pet_191",
    "name": "Optic Gear Raven",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and titanium chrome trim."
  },
  {
    "id": "pet_192",
    "name": "Clockwork Falcon Bot",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and amber glow trim."
  },
  {
    "id": "pet_193",
    "name": "Wise Falcon Bot",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and neon magenta trim."
  },
  {
    "id": "pet_194",
    "name": "Obsidian Falcon Bot",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and gilded gold trim."
  },
  {
    "id": "pet_195",
    "name": "Brass Falcon Bot",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and plasma blue trim."
  },
  {
    "id": "pet_196",
    "name": "Nocturnal Falcon Bot",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and electric violet trim."
  },
  {
    "id": "pet_197",
    "name": "Optic Falcon Bot",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and quantum aqua trim."
  },
  {
    "id": "pet_198",
    "name": "Clockwork Aero Hawk",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and crimson laser trim."
  },
  {
    "id": "pet_199",
    "name": "Wise Aero Hawk",
    "category": "pets",
    "archetype": "cyber_owl",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Autonomous 3D robotic companion with interactive behavior algorithms and matrix emerald trim."
  }
];
