export const skins = [
  // ---------------------------------------------------------------------------
  // 1. CYBER SUIT ARCHETYPE (IDs skin_0 - skin_9)
  // Tactical cybernetic operatives & street enforcers
  // ---------------------------------------------------------------------------
  {
    id: "skin_0",
    name: "Neon Enforcer",
    category: "skins",
    archetype: "cyber_suit",
    variant: "tactical_visor",
    tier: "free",
    rarity: "common",
    color: "#00f0ff",
    secondaryColor: "#003b46",
    accentColor: "#ffffff",
    paletteName: "Cyber Cyan",
    description: "Standard tactical patrol armor with dual wing antennas, high-intensity neon cyan brow visor, and responsive reactor core.",
    previewColor: "#00f0ff"
  },
  {
    id: "skin_1",
    name: "Crimson Striker",
    category: "skins",
    archetype: "cyber_suit",
    variant: "laser_scout",
    tier: "free",
    rarity: "common",
    color: "#f43f5e",
    secondaryColor: "#4c0519",
    accentColor: "#fb7185",
    paletteName: "Crimson Laser",
    description: "Lightweight urban reconnaissance armor with an asymmetric tactical monocle HUD and red crosshair targeting optic.",
    previewColor: "#f43f5e"
  },
  {
    id: "skin_2",
    name: "Amber Sentinel",
    category: "skins",
    archetype: "cyber_suit",
    variant: "riot_shield",
    tier: "coffee",
    rarity: "rare",
    color: "#f59e0b",
    secondaryColor: "#451a03",
    accentColor: "#fef3c7",
    paletteName: "Amber Hazard",
    description: "Heavy reinforced blast armor featuring a hardened ballistic neck gorget and dual flashing amber emergency strobes.",
    previewColor: "#f59e0b"
  },
  {
    id: "skin_3",
    name: "Electric Specter",
    category: "skins",
    archetype: "cyber_suit",
    variant: "cyber_horns",
    tier: "coffee",
    rarity: "rare",
    color: "#a855f7",
    secondaryColor: "#2e1065",
    accentColor: "#e9d5ff",
    paletteName: "Electric Violet",
    description: "Covert electronic warfare suit equipped with twin swept-back cyber horn sensor antennas and purple pulse conduits.",
    previewColor: "#a855f7"
  },
  {
    id: "skin_4",
    name: "Gilded Vanguard",
    category: "skins",
    archetype: "cyber_suit",
    variant: "crown_radiator",
    tier: "coffee",
    rarity: "rare",
    color: "#fbbf24",
    secondaryColor: "#78350f",
    accentColor: "#ffffff",
    paletteName: "Gilded Sovereign",
    description: "Ceremonial commander battlesuit crowned with triple golden heatsink radiators and an auric gold arc reactor.",
    previewColor: "#fbbf24"
  },
  {
    id: "skin_5",
    name: "Acid Hazard",
    category: "skins",
    archetype: "cyber_suit",
    variant: "gas_respirator",
    tier: "lunch",
    rarity: "epic",
    color: "#84cc16",
    secondaryColor: "#1a2e05",
    accentColor: "#bef264",
    paletteName: "Toxic Lime",
    description: "Contaminated zone exosuit with dual canister filtration respirators and high-visibility yellow hazard chevron stripes.",
    previewColor: "#84cc16"
  },
  {
    id: "skin_6",
    name: "Frost Phantom",
    category: "skins",
    archetype: "cyber_suit",
    variant: "prism_goggles",
    tier: "lunch",
    rarity: "epic",
    color: "#38bdf8",
    secondaryColor: "#082f49",
    accentColor: "#e0f2fe",
    paletteName: "Glacial Ice",
    description: "Cryo-adapted high altitude armor featuring hexagonal dual prism goggles with icy blue internal laser refraction.",
    previewColor: "#38bdf8"
  },
  {
    id: "skin_7",
    name: "Obsidian Ronin",
    category: "skins",
    archetype: "cyber_suit",
    variant: "samurai_crest",
    tier: "lunch",
    rarity: "epic",
    color: "#e11d48",
    secondaryColor: "#18181b",
    accentColor: "#fda4af",
    paletteName: "Blood Ruby",
    description: "Cybernetic kabuto armor with a forward-swept golden horn crest and dual neck-collar tantō blade sheaths.",
    previewColor: "#e11d48"
  },
  {
    id: "skin_8",
    name: "Solar Overdrive",
    category: "skins",
    archetype: "cyber_suit",
    variant: "overdrive_vents",
    tier: "vip",
    rarity: "legendary",
    color: "#ff0055",
    secondaryColor: "#3f0015",
    accentColor: "#ffaa00",
    paletteName: "Plasma Magenta",
    description: "Hyper-clocked prototype suit featuring swept aerodynamic cooling fins glowing red-hot with plasma exhaust venting.",
    previewColor: "#ff0055"
  },
  {
    id: "skin_9",
    name: "Quantum Sovereign",
    category: "skins",
    archetype: "cyber_suit",
    variant: "holo_shroud",
    tier: "vip",
    rarity: "mythic",
    color: "#ffffff",
    secondaryColor: "#00f0ff",
    accentColor: "#38bdf8",
    paletteName: "Pure Platinum",
    description: "Legendary supreme operative armor featuring a floating crystalline holographic shroud and dual quantum emitters.",
    previewColor: "#ffffff"
  },

  // ---------------------------------------------------------------------------
  // 2. MECHA PILOT ARCHETYPE (IDs skin_10 - skin_19)
  // Heavy robotic battlesuits, armored frames & titans
  // ---------------------------------------------------------------------------
  {
    id: "skin_10",
    name: "Apex Frame",
    category: "skins",
    archetype: "mecha_pilot",
    variant: "v_fin",
    tier: "free",
    rarity: "common",
    color: "#3b82f6",
    secondaryColor: "#172554",
    accentColor: "#93c5fd",
    paletteName: "Cobalt Mech",
    description: "Iconic military mobile suit frame featuring a prominent golden V-Fin antenna crest and reinforced chin guard.",
    previewColor: "#3b82f6"
  },
  {
    id: "skin_11",
    name: "Heavy Colossus",
    category: "skins",
    archetype: "mecha_pilot",
    variant: "blast_shield",
    tier: "free",
    rarity: "common",
    color: "#94a3b8",
    secondaryColor: "#1e293b",
    accentColor: "#ffffff",
    paletteName: "Titanium Steel",
    description: "Super-heavy trench battlesuit equipped with a massive armored blast visor, dual searchlights, and boxy shoulder pods.",
    previewColor: "#94a3b8"
  },
  {
    id: "skin_12",
    name: "Berserk EVA",
    category: "skins",
    archetype: "mecha_pilot",
    variant: "eva_horn",
    tier: "coffee",
    rarity: "rare",
    color: "#9333ea",
    secondaryColor: "#22c55e",
    accentColor: "#4ade80",
    paletteName: "EVA Purple",
    description: "Unstable biomechanical pilot suit sporting a tall frontal unicorn horn blade, neon green teeth slits, and shoulder pylons.",
    previewColor: "#9333ea"
  },
  {
    id: "skin_13",
    name: "Iron Juggernaut",
    category: "skins",
    archetype: "mecha_pilot",
    variant: "cage_grille",
    tier: "coffee",
    rarity: "rare",
    color: "#d97706",
    secondaryColor: "#451a03",
    accentColor: "#fbbf24",
    paletteName: "Industrial Ochre",
    description: "Hardened mining rig armor with a heavy industrial cage grille faceplate and twin vertical smokestack exhausts.",
    previewColor: "#d97706"
  },
  {
    id: "skin_14",
    name: "Crimson Warmachine",
    category: "skins",
    archetype: "mecha_pilot",
    variant: "missile_pod",
    tier: "coffee",
    rarity: "rare",
    color: "#dc2626",
    secondaryColor: "#450a0a",
    accentColor: "#fca5a5",
    paletteName: "War Crimson",
    description: "Artillery command rig with twin shoulder-mounted micro-missile pods and a crimson HUD targeting scope.",
    previewColor: "#dc2626"
  },
  {
    id: "skin_15",
    name: "Plasma Dreadnought",
    category: "skins",
    archetype: "mecha_pilot",
    variant: "quad_array",
    tier: "lunch",
    rarity: "epic",
    color: "#06b6d4",
    secondaryColor: "#083344",
    accentColor: "#67e8f9",
    paletteName: "Plasma Cyan",
    description: "Naval assault mech featuring a quad-mast sensor antenna array and a high-output chest plasma reactor core.",
    previewColor: "#06b6d4"
  },
  {
    id: "skin_16",
    name: "Cyber Aegis",
    category: "skins",
    archetype: "mecha_pilot",
    variant: "halo_shield",
    tier: "lunch",
    rarity: "epic",
    color: "#10b981",
    secondaryColor: "#064e3b",
    accentColor: "#6ee7b7",
    paletteName: "Emerald Aegis",
    description: "Heavy defensive chassis armed with a hydraulic reinforced neck brace and dual hexagonal energy shields on shoulders.",
    previewColor: "#10b981"
  },
  {
    id: "skin_17",
    name: "Dread Goliath",
    category: "skins",
    archetype: "mecha_pilot",
    variant: "ram_horns",
    tier: "lunch",
    rarity: "epic",
    color: "#64748b",
    secondaryColor: "#ef4444",
    accentColor: "#f87171",
    paletteName: "Gunmetal Red",
    description: "Demolition battlesuit with massive curved mecha ramming horns and an intimidating single-slit red mono-eye.",
    previewColor: "#64748b"
  },
  {
    id: "skin_18",
    name: "Orbital Titan",
    category: "skins",
    archetype: "mecha_pilot",
    variant: "radar_dish",
    tier: "vip",
    rarity: "legendary",
    color: "#eab308",
    secondaryColor: "#1c1917",
    accentColor: "#fef08a",
    paletteName: "Solar Titan",
    description: "Deep-space defense frame with an orbital parabolic telemetry radar dish and dual high-gain comm masts.",
    previewColor: "#eab308"
  },
  {
    id: "skin_19",
    name: "Omega Destroyer",
    category: "skins",
    archetype: "mecha_pilot",
    variant: "hyper_wings",
    tier: "vip",
    rarity: "mythic",
    color: "#be123c",
    secondaryColor: "#4c0519",
    accentColor: "#fb7185",
    paletteName: "Omega Dark",
    description: "Ultimate planetary assault mech featuring swept hyper-drive flight wings, twin head cannons, and red-shifted thrusters.",
    previewColor: "#be123c"
  },

  // ---------------------------------------------------------------------------
  // 3. STEALTH NINJA ARCHETYPE (IDs skin_20 - skin_29)
  // Cybernetic shinobi, shadow infiltrators & blade masters
  // ---------------------------------------------------------------------------
  {
    id: "skin_20",
    name: "Shadow Shinobi",
    category: "skins",
    archetype: "stealth_ninja",
    variant: "flowing_headband",
    tier: "free",
    rarity: "common",
    color: "#6366f1",
    secondaryColor: "#1e1b4b",
    accentColor: "#a5b4fc",
    paletteName: "Midnight Indigo",
    description: "Classic cyber shinobi gear with a polished titanium forehead hitai-ate plate and long flowing indigo cloth headband tails.",
    previewColor: "#6366f1"
  },
  {
    id: "skin_21",
    name: "Silent Infiltrator",
    category: "skins",
    archetype: "stealth_ninja",
    variant: "tactical_cowl",
    tier: "free",
    rarity: "common",
    color: "#10b981",
    secondaryColor: "#022c22",
    accentColor: "#34d399",
    paletteName: "Night Emerald",
    description: "Black-ops balaclava shroud featuring a single glowing emerald thermal-optical monocle sensor with target acquisition.",
    previewColor: "#10b981"
  },
  {
    id: "skin_22",
    name: "Kage Oni",
    category: "skins",
    archetype: "stealth_ninja",
    variant: "oni_mask",
    tier: "coffee",
    rarity: "rare",
    color: "#ef4444",
    secondaryColor: "#450a0a",
    accentColor: "#ffffff",
    paletteName: "Demon Crimson",
    description: "Intimidating Japanese Oni demon half-mask equipped with glowing porcelain fangs and dual menacing crimson horns.",
    previewColor: "#ef4444"
  },
  {
    id: "skin_23",
    name: "Cyber Kitsune",
    category: "skins",
    archetype: "stealth_ninja",
    variant: "kitsune_ears",
    tier: "coffee",
    rarity: "rare",
    color: "#f43f5e",
    secondaryColor: "#ffe4e6",
    accentColor: "#fb7185",
    paletteName: "Sakura Blossom",
    description: "Agile spirit operative suit featuring pointed cybernetic fox ears and delicate sensor whisker decals along the cheeks.",
    previewColor: "#f43f5e"
  },
  {
    id: "skin_24",
    name: "Cyber Ronin Kasa",
    category: "skins",
    archetype: "stealth_ninja",
    variant: "conical_kasa",
    tier: "coffee",
    rarity: "rare",
    color: "#eab308",
    secondaryColor: "#18181b",
    accentColor: "#fef08a",
    paletteName: "Ronin Gold",
    description: "Masterless wanderer gear sporting a wide-brim conical cyber kasa straw hat with an under-rim glowing neon yellow circuit ring.",
    previewColor: "#eab308"
  },
  {
    id: "skin_25",
    name: "Obsidian Blade",
    category: "skins",
    archetype: "stealth_ninja",
    variant: "twin_katanas",
    tier: "lunch",
    rarity: "epic",
    color: "#14b8a6",
    secondaryColor: "#042f2e",
    accentColor: "#5eead4",
    paletteName: "Teal Phantom",
    description: "Dual-wield assassin outfit featuring crossed holographic katana sheaths on the back and a blindfold-style sensory visor.",
    previewColor: "#14b8a6"
  },
  {
    id: "skin_26",
    name: "Raven Tengu",
    category: "skins",
    archetype: "stealth_ninja",
    variant: "tengu_beak",
    tier: "lunch",
    rarity: "epic",
    color: "#8b5cf6",
    secondaryColor: "#1e1b4b",
    accentColor: "#c4b5fd",
    paletteName: "Amethyst Raven",
    description: "Mountain phantom gear with an aerodynamic raven beak half-mask and razor-sharp feathered blade pauldrons.",
    previewColor: "#8b5cf6"
  },
  {
    id: "skin_27",
    name: "Smoke Wraith",
    category: "skins",
    archetype: "stealth_ninja",
    variant: "veil_shroud",
    tier: "lunch",
    rarity: "epic",
    color: "#94a3b8",
    secondaryColor: "#0f172a",
    accentColor: "#e2e8f0",
    paletteName: "Slate Mist",
    description: "Infiltration gear wrapped in a hooded dark nanofiber veil with glowing horizontal eye slits and faint smoke dissipation.",
    previewColor: "#94a3b8"
  },
  {
    id: "skin_28",
    name: "Midnight Duelist",
    category: "skins",
    archetype: "stealth_ninja",
    variant: "scythe_crest",
    tier: "vip",
    rarity: "legendary",
    color: "#ec4899",
    secondaryColor: "#500724",
    accentColor: "#f472b6",
    paletteName: "Cyber Magenta",
    description: "Elite arena champion gear featuring an elegant crescent moon scythe crest on the forehead and twin kunai collar pins.",
    previewColor: "#ec4899"
  },
  {
    id: "skin_29",
    name: "Void Assassin",
    category: "skins",
    archetype: "stealth_ninja",
    variant: "void_mask",
    tier: "vip",
    rarity: "mythic",
    color: "#00f0ff",
    secondaryColor: "#020617",
    accentColor: "#ffffff",
    paletteName: "Void Shinobi",
    description: "Pitch-black stealth armor absorbing 99% of light, featuring glowing cyan runic kanji hovering mysteriously in front of the face.",
    previewColor: "#00f0ff"
  },

  // ---------------------------------------------------------------------------
  // 4. MATRIX HACKER ARCHETYPE (IDs skin_30 - skin_39)
  // Netrunners, underground cryptographers & terminal phreaks
  // ---------------------------------------------------------------------------
  {
    id: "skin_30",
    name: "Root Netrunner",
    category: "skins",
    archetype: "matrix_hacker",
    variant: "hoodie_cowl",
    tier: "free",
    rarity: "common",
    color: "#10b981",
    secondaryColor: "#022c22",
    accentColor: "#6ee7b7",
    paletteName: "Phosphor Terminal",
    description: "Underground hacker suit with a deep oversized hooded cowl dripping with vertical green phosphorescent digital code streams.",
    previewColor: "#10b981"
  },
  {
    id: "skin_31",
    name: "Binary Coder",
    category: "skins",
    archetype: "matrix_hacker",
    variant: "vr_goggles",
    tier: "free",
    rarity: "common",
    color: "#06b6d4",
    secondaryColor: "#083344",
    accentColor: "#67e8f9",
    paletteName: "Terminal Cyan",
    description: "Classic retro cyberdeck enthusiast gear equipped with chunky rectangular VR goggles and an omnidirectional radio antenna.",
    previewColor: "#06b6d4"
  },
  {
    id: "skin_32",
    name: "ZeroDay Daemon",
    category: "skins",
    archetype: "matrix_hacker",
    variant: "daemon_horns",
    tier: "coffee",
    rarity: "rare",
    color: "#ef4444",
    secondaryColor: "#450a0a",
    accentColor: "#fca5a5",
    paletteName: "Kernel Panic",
    description: "Malicious exploit runner sporting a dark beanie cowl with integrated red cyber devil horns and glowing memory fault LEDs.",
    previewColor: "#ef4444"
  },
  {
    id: "skin_33",
    name: "Glitch Cracker",
    category: "skins",
    archetype: "matrix_hacker",
    variant: "glitch_halo",
    tier: "coffee",
    rarity: "rare",
    color: "#eab308",
    secondaryColor: "#422006",
    accentColor: "#fef08a",
    paletteName: "Bug Amber",
    description: "Glitching outfit surrounded by jittering holographic wireframe shards and corrupted polygon artifacts hovering in 3D space.",
    previewColor: "#eab308"
  },
  {
    id: "skin_34",
    name: "Defrag Nethead",
    category: "skins",
    archetype: "matrix_hacker",
    variant: "floating_hud",
    tier: "coffee",
    rarity: "rare",
    color: "#3b82f6",
    secondaryColor: "#172554",
    accentColor: "#93c5fd",
    paletteName: "Root Blue",
    description: "High-spec sysadmin gear featuring a floating terminal prompt HUD window [root@sys ~]# hovering persistently beside the ear.",
    previewColor: "#3b82f6"
  },
  {
    id: "skin_35",
    name: "Acid Breacher",
    category: "skins",
    archetype: "matrix_hacker",
    variant: "respirator_eq",
    tier: "lunch",
    rarity: "epic",
    color: "#a3e635",
    secondaryColor: "#14532d",
    accentColor: "#d9f99d",
    paletteName: "Toxic Byte",
    description: "Cybergoth infiltrator gear featuring a twin respirator mask fitted with responsive multi-color equalizer audio VU bars.",
    previewColor: "#a3e635"
  },
  {
    id: "skin_36",
    name: "Overclocked Phreak",
    category: "skins",
    archetype: "matrix_hacker",
    variant: "heatsink_fins",
    tier: "lunch",
    rarity: "epic",
    color: "#f97316",
    secondaryColor: "#431407",
    accentColor: "#fed7aa",
    paletteName: "Copper Thermal",
    description: "Extreme liquid-cooled rig featuring exposed copper cranium heatsink cooling fins glowing brightly with molten thermal heat.",
    previewColor: "#f97316"
  },
  {
    id: "skin_37",
    name: "Fiber Cablehead",
    category: "skins",
    archetype: "matrix_hacker",
    variant: "cable_dreads",
    tier: "lunch",
    rarity: "epic",
    color: "#8b5cf6",
    secondaryColor: "#2e1065",
    accentColor: "#c4b5fd",
    paletteName: "Fiber Optics",
    description: "Deep-net diving suit with a cascade of glowing fiber-optic cable dreadlocks flowing down behind the helmet.",
    previewColor: "#8b5cf6"
  },
  {
    id: "skin_38",
    name: "Anonymous Skull",
    category: "skins",
    archetype: "matrix_hacker",
    variant: "cyber_skull",
    tier: "vip",
    rarity: "legendary",
    color: "#f43f5e",
    secondaryColor: "#0f172a",
    accentColor: "#fb7185",
    paletteName: "Exploit Red",
    description: "Legendary hacktivist avatar equipped with a glowing cybernetic skull faceplate streaming live memory disassembly code.",
    previewColor: "#f43f5e"
  },
  {
    id: "skin_39",
    name: "Architect AI",
    category: "skins",
    archetype: "matrix_hacker",
    variant: "wireframe_cube",
    tier: "vip",
    rarity: "mythic",
    color: "#00f0ff",
    secondaryColor: "#050510",
    accentColor: "#a5f3fc",
    paletteName: "Tesseract Neon",
    description: "Sentient entity manifestation featuring a rotating 4D holographic wireframe tesseract cube encapsulating the entire helm.",
    previewColor: "#00f0ff"
  },

  // ---------------------------------------------------------------------------
  // 5. CELESTIAL ASTRO ARCHETYPE (IDs skin_40 - skin_49)
  // Deep-space explorers, cosmic voyagers & void entities
  // ---------------------------------------------------------------------------
  {
    id: "skin_40",
    name: "Solar Voyager",
    category: "skins",
    archetype: "celestial_astro",
    variant: "bubble_dome",
    tier: "free",
    rarity: "common",
    color: "#f59e0b",
    secondaryColor: "#451a03",
    accentColor: "#fde68a",
    paletteName: "Sun Gold",
    description: "High-visibility EVA exploration suit with a large spherical gold-mirrored bubble dome helmet and high-output floodlight.",
    previewColor: "#f59e0b"
  },
  {
    id: "skin_41",
    name: "Lunar Cosmonaut",
    category: "skins",
    archetype: "celestial_astro",
    variant: "lunar_pack",
    tier: "free",
    rarity: "common",
    color: "#e2e8f0",
    secondaryColor: "#1e293b",
    accentColor: "#ffffff",
    paletteName: "Apollo White",
    description: "Classic lunar surface suit with pressurized white composite shell, gold foil visor rim, and dual VHF telemetry whip antennas.",
    previewColor: "#e2e8f0"
  },
  {
    id: "skin_42",
    name: "Cosmic Starfarer",
    category: "skins",
    archetype: "celestial_astro",
    variant: "sunburst_halo",
    tier: "coffee",
    rarity: "rare",
    color: "#facc15",
    secondaryColor: "#713f12",
    accentColor: "#fef9c3",
    paletteName: "Starlight Gold",
    description: "Astral navigation suit featuring an eight-point celestial sunburst corona halo floating radiant behind the helmet.",
    previewColor: "#facc15"
  },
  {
    id: "skin_43",
    name: "Nebula Drifter",
    category: "skins",
    archetype: "celestial_astro",
    variant: "saturn_ring",
    tier: "coffee",
    rarity: "rare",
    color: "#c084fc",
    secondaryColor: "#3b0764",
    accentColor: "#e9d5ff",
    paletteName: "Nebula Lilac",
    description: "Deep space nomad suit encircled by an ethereal tilted planetary ring with microscopic luminous moonlets orbiting the head.",
    previewColor: "#c084fc"
  },
  {
    id: "skin_44",
    name: "Astral Pioneer",
    category: "skins",
    archetype: "celestial_astro",
    variant: "star_crown",
    tier: "coffee",
    rarity: "rare",
    color: "#38bdf8",
    secondaryColor: "#082f49",
    accentColor: "#bae6fd",
    paletteName: "Sky Azure",
    description: "Interstellar boundary scout crowned with five faceted starlight crystals that emit gentle twinkling photonic pulses.",
    previewColor: "#38bdf8"
  },
  {
    id: "skin_45",
    name: "Void Nomad",
    category: "skins",
    archetype: "celestial_astro",
    variant: "eclipse_corona",
    tier: "lunch",
    rarity: "epic",
    color: "#64748b",
    secondaryColor: "#020617",
    accentColor: "#94a3b8",
    paletteName: "Void Obsidian",
    description: "Black hole survey suit enclosed in a dark singularity mask with a shimmering golden accretion disk corona rim.",
    previewColor: "#64748b"
  },
  {
    id: "skin_46",
    name: "Supernova Stargazer",
    category: "skins",
    archetype: "celestial_astro",
    variant: "pulsar_spires",
    tier: "lunch",
    rarity: "epic",
    color: "#f43f5e",
    secondaryColor: "#4c0519",
    accentColor: "#fda4af",
    paletteName: "Supernova Red",
    description: "High-energy stellar researcher suit with dual vertical pulsar radiation beam spires extending from the helmet apex and chin.",
    previewColor: "#f43f5e"
  },
  {
    id: "skin_47",
    name: "Aurora Oracle",
    category: "skins",
    archetype: "celestial_astro",
    variant: "aurora_ribbons",
    tier: "lunch",
    rarity: "epic",
    color: "#2dd4bf",
    secondaryColor: "#042f2e",
    accentColor: "#99f6e4",
    paletteName: "Aurora Borealis",
    description: "Mystic spacefarer attire with flowing translucent polar aurora ribbons waving gracefully in zero-gravity above the helmet.",
    previewColor: "#2dd4bf"
  },
  {
    id: "skin_48",
    name: "Eclipse Zenith",
    category: "skins",
    archetype: "celestial_astro",
    variant: "angel_wings",
    tier: "vip",
    rarity: "legendary",
    color: "#a855f7",
    secondaryColor: "#1e1b4b",
    accentColor: "#d8b4fe",
    paletteName: "Cosmic Amethyst",
    description: "Exalted celestial avatar featuring sweeping cybernetic energy wings on the shoulders and a luminous floating cosmic nimbus.",
    previewColor: "#a855f7"
  },
  {
    id: "skin_49",
    name: "Omega Singularity",
    category: "skins",
    archetype: "celestial_astro",
    variant: "singularity_core",
    tier: "vip",
    rarity: "mythic",
    color: "#ffffff",
    secondaryColor: "#030712",
    accentColor: "#38bdf8",
    paletteName: "Event Horizon",
    description: "Mythic entity existing at the edge of space-time, featuring a gravitational light-warping lens ring and orbiting cosmic motes.",
    previewColor: "#ffffff"
  }
];
