export const trophies = [
  {
    "id": "trophy_0",
    "name": "Master Golden Key",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "free",
    "rarity": "common",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_1",
    "name": "Architechtural Golden Key",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "free",
    "rarity": "common",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_2",
    "name": "Genesis Golden Key",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "free",
    "rarity": "common",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_3",
    "name": "VIP Golden Key",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_4",
    "name": "Legendary Golden Key",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_5",
    "name": "Master Root Passkey",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_6",
    "name": "Architechtural Root Passkey",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_7",
    "name": "Genesis Root Passkey",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_8",
    "name": "VIP Root Passkey",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_9",
    "name": "Legendary Root Passkey",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_10",
    "name": "Master Cryptographic Token",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_11",
    "name": "Architechtural Cryptographic Token",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_12",
    "name": "Genesis Cryptographic Token",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_13",
    "name": "VIP Cryptographic Token",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_14",
    "name": "Legendary Cryptographic Token",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_15",
    "name": "Master Sovereign Seal",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_16",
    "name": "Architechtural Sovereign Seal",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_17",
    "name": "Genesis Sovereign Seal",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_18",
    "name": "VIP Sovereign Seal",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_19",
    "name": "Legendary Sovereign Seal",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_20",
    "name": "Master Golden Key",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_21",
    "name": "Architechtural Golden Key",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_22",
    "name": "Genesis Golden Key",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_23",
    "name": "VIP Golden Key",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_24",
    "name": "Legendary Golden Key",
    "category": "trophies",
    "archetype": "golden_key",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_25",
    "name": "Nanometer Silicon Wafer Plaque",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "free",
    "rarity": "common",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_26",
    "name": "Monolithic Silicon Wafer Plaque",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "free",
    "rarity": "common",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_27",
    "name": "Wafer-Scale Silicon Wafer Plaque",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "free",
    "rarity": "common",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_28",
    "name": "Die-Shot Silicon Wafer Plaque",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_29",
    "name": "Pure Silicon Silicon Wafer Plaque",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_30",
    "name": "Nanometer ASIC Trophy",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_31",
    "name": "Monolithic ASIC Trophy",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_32",
    "name": "Wafer-Scale ASIC Trophy",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_33",
    "name": "Die-Shot ASIC Trophy",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_34",
    "name": "Pure Silicon ASIC Trophy",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_35",
    "name": "Nanometer Quantum Core Slab",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_36",
    "name": "Monolithic Quantum Core Slab",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_37",
    "name": "Wafer-Scale Quantum Core Slab",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_38",
    "name": "Die-Shot Quantum Core Slab",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_39",
    "name": "Pure Silicon Quantum Core Slab",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_40",
    "name": "Nanometer Semiconductor Disc",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_41",
    "name": "Monolithic Semiconductor Disc",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_42",
    "name": "Wafer-Scale Semiconductor Disc",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_43",
    "name": "Die-Shot Semiconductor Disc",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_44",
    "name": "Pure Silicon Semiconductor Disc",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_45",
    "name": "Nanometer Silicon Wafer Plaque",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_46",
    "name": "Monolithic Silicon Wafer Plaque",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_47",
    "name": "Wafer-Scale Silicon Wafer Plaque",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_48",
    "name": "Die-Shot Silicon Wafer Plaque",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_49",
    "name": "Pure Silicon Silicon Wafer Plaque",
    "category": "trophies",
    "archetype": "silicon_wafer",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_50",
    "name": "Faceted Quantum Crystal",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "free",
    "rarity": "common",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_51",
    "name": "Prismatic Quantum Crystal",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "free",
    "rarity": "common",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_52",
    "name": "Refractive Quantum Crystal",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "free",
    "rarity": "common",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_53",
    "name": "Resonant Quantum Crystal",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_54",
    "name": "Iridescent Quantum Crystal",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_55",
    "name": "Faceted Pyramid Monolith",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_56",
    "name": "Prismatic Pyramid Monolith",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_57",
    "name": "Refractive Pyramid Monolith",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_58",
    "name": "Resonant Pyramid Monolith",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_59",
    "name": "Iridescent Pyramid Monolith",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_60",
    "name": "Faceted Polygonal Relic",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_61",
    "name": "Prismatic Polygonal Relic",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_62",
    "name": "Refractive Polygonal Relic",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_63",
    "name": "Resonant Polygonal Relic",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_64",
    "name": "Iridescent Polygonal Relic",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_65",
    "name": "Faceted Crystal Shard",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_66",
    "name": "Prismatic Crystal Shard",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_67",
    "name": "Refractive Crystal Shard",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_68",
    "name": "Resonant Crystal Shard",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_69",
    "name": "Iridescent Crystal Shard",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_70",
    "name": "Faceted Quantum Crystal",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_71",
    "name": "Prismatic Quantum Crystal",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_72",
    "name": "Refractive Quantum Crystal",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_73",
    "name": "Resonant Quantum Crystal",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_74",
    "name": "Iridescent Quantum Crystal",
    "category": "trophies",
    "archetype": "quantum_crystal",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_75",
    "name": "Zero-Day Diamond Bug Trophy",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "free",
    "rarity": "common",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_76",
    "name": "Bounty Hunter Diamond Bug Trophy",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "free",
    "rarity": "common",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_77",
    "name": "Platinum Diamond Bug Trophy",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "free",
    "rarity": "common",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_78",
    "name": "Defect Hunter Diamond Bug Trophy",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_79",
    "name": "Titanium Diamond Bug Trophy",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_80",
    "name": "Zero-Day Golden Beetle",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_81",
    "name": "Bounty Hunter Golden Beetle",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_82",
    "name": "Platinum Golden Beetle",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_83",
    "name": "Defect Hunter Golden Beetle",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "coffee",
    "rarity": "rare",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_84",
    "name": "Titanium Golden Beetle",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_85",
    "name": "Zero-Day SecOps Medal",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_86",
    "name": "Bounty Hunter SecOps Medal",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_87",
    "name": "Platinum SecOps Medal",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_88",
    "name": "Defect Hunter SecOps Medal",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_89",
    "name": "Titanium SecOps Medal",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_90",
    "name": "Zero-Day Vulnerability Relic",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#00f0ff",
    "secondaryColor": "#003b46",
    "paletteName": "Cyber Cyan",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_91",
    "name": "Bounty Hunter Vulnerability Relic",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "lunch",
    "rarity": "epic",
    "color": "#10b981",
    "secondaryColor": "#022c22",
    "paletteName": "Matrix Emerald",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_92",
    "name": "Platinum Vulnerability Relic",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "lunch",
    "rarity": "legendary",
    "color": "#f43f5e",
    "secondaryColor": "#4c0519",
    "paletteName": "Crimson Laser",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_93",
    "name": "Defect Hunter Vulnerability Relic",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#06b6d4",
    "secondaryColor": "#083344",
    "paletteName": "Quantum Aqua",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_94",
    "name": "Titanium Vulnerability Relic",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#a855f7",
    "secondaryColor": "#2e1065",
    "paletteName": "Electric Violet",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_95",
    "name": "Zero-Day Diamond Bug Trophy",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#3b82f6",
    "secondaryColor": "#172554",
    "paletteName": "Plasma Blue",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_96",
    "name": "Bounty Hunter Diamond Bug Trophy",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "vip",
    "rarity": "legendary",
    "color": "#fbbf24",
    "secondaryColor": "#78350f",
    "paletteName": "Gilded Gold",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_97",
    "name": "Platinum Diamond Bug Trophy",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#ff007f",
    "secondaryColor": "#4a0024",
    "paletteName": "Neon Magenta",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_98",
    "name": "Defect Hunter Diamond Bug Trophy",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#f59e0b",
    "secondaryColor": "#451a03",
    "paletteName": "Amber Glow",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  },
  {
    "id": "trophy_99",
    "name": "Titanium Diamond Bug Trophy",
    "category": "trophies",
    "archetype": "diamond_bug",
    "tier": "vip",
    "rarity": "mythic",
    "color": "#e2e8f0",
    "secondaryColor": "#1e293b",
    "paletteName": "Titanium Chrome",
    "description": "Faceted 3D metallic desktop monument awarded for engineering milestones and supporter contributions."
  }
];
